fix parent_id hidden field issue
ShehrozIrfan/comment_tree_app pull request #66
Opened 2023-05-12 15:00 UTC by muhammadshoaib0k0

2023-05-12 15:14 UTC, ShehrozIrfan commented
@muhammadshoaib0k0 
Please create a short video, demonstrating the flow.

2023-05-12 16:14 UTC, muhammadshoaib0k0 commented
> @muhammadshoaib0k0 Please create a short video, demonstrating the flow.
https://www.loom.com/share/a8789379f3bb442881d2ff3ba1a14bf5

2023-05-12 16:40 UTC, ShehrozIrfan commented on app/controllers/comments_controller.rb
> +    # Check if the parent ID from the submitted form data matches the ID from the referrer URL
remove this comment.

2023-05-12 16:40 UTC, ShehrozIrfan commented on app/controllers/comments_controller.rb
> +      # Redirect to the parent comment page with an error message if the parent ID is invalid
this one also.

2023-05-12 16:40 UTC, ShehrozIrfan commented on app/controllers/comments_controller.rb
> +      # Save the response and redirect to the parent comment page with a success message
this one also

2023-05-12 16:40 UTC, ShehrozIrfan commented on app/controllers/comments_controller.rb
> +        # Return a JSON response with errors if the response could not be saved
this one also

2023-05-12 16:40 UTC, ShehrozIrfan requested changes
Good catch.

Just a minor update, please remove all the comments added.

2023-05-12 16:55 UTC, muhammadshoaib0k0 commented on app/controllers/comments_controller.rb
> +    # Check if the parent ID from the submitted form data matches the ID from the referrer URL
Done

2023-05-12 16:55 UTC, muhammadshoaib0k0 commented on app/controllers/comments_controller.rb
> +      # Redirect to the parent comment page with an error message if the parent ID is invalid
Done

2023-05-12 16:55 UTC, muhammadshoaib0k0 commented on app/controllers/comments_controller.rb
> +      # Save the response and redirect to the parent comment page with a success message
Done

2023-05-12 16:55 UTC, muhammadshoaib0k0 commented on app/controllers/comments_controller.rb
> +        # Return a JSON response with errors if the response could not be saved
Done

2023-05-13 06:15 UTC, ShehrozIrfan approved these changes
LGTM.

Thanks for your contribution 🚀

@muhammadshoaib0k0 You can follow me and star this repo for further updates.
Thanks.

2023-05-13 06:15 UTC, merged